version: '2'

services:
  mankeli:
    build:
      context: ./
    image: mankeli_dev
    volumes:
      - ./data:/srv/flask_app/data
    ports:
      - '9090:80'
    environment:
      - TOKEN=DEVTOKEN
    container_name: mankeli
